modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="mindustryinmincraft"
version="0.0.1"
displayName="MindustryInMincraft"
credits="r/mindustry and discord.gg/mindustry"
displayURL="https://mcreator.net"
authors="YeetLand1"
description='''
Mindustry in Minecraft
'''

[[dependencies.mindustryinmincraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




