modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="mindustryinminecraft"
version="0.0.1"
displayName="MindustryInMinecraft"
credits="Vatisco"
displayURL="https://mcreator.net"
authors="YeetLand1"
description='''
Mindustry in Minecraft
'''

[[dependencies.mindustryinminecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




